### ISSUE TITLE
Increase use of issues to track needed work

### ISSUE THREAD

**Issue by dward2** [mhuss93/bme547final#10]
@mhuss93 @katrina-barth @IakovRach In a quick look through your repository, I would increase your use of "Issues" to track the work you need to do.  That will be one of the grading criteria.

**Comment by katrina-barth** [comment]
Dr. Ward,

Thank you for pointing this out to us!! We will start using more.

Best,
-Katrina


Katrina Barth

Viventi Lab  -  PhD Student

Department of Biomedical Engineering

Duke University

________________________________

**Comment by dward2** [comment]
@katrina-barth @mhuss93 @IakovRach I see you have added some additional issues to track your work items.  Good.  We will also be looking for some intra-team communication done through the comments in these issues.  So, keep that in mind as you are working together over the next few days.

Also, I know I gave an extension through this weekend, but it looks like you guys still have a lot of work to do.  I would make some firm plans on how you are going to get everything done between now and Sunday.
