### ISSUE TITLE
Connect GUI Image Upload and Download with Server

### ISSUE THREAD

**Issue by katrina-barth** [mhuss93/bme547final#15]

**Comment by minhajh** [comment]
To upload a base image: send POST request to route '/api/upload_user_image'.

The posted json needs the following fields:

- [ ] 'user_id' (string, with unique user identifier)

- [x]  'filename' (string)

- [x] 'extension' (string)

- [x] 'image' (string - base64 encoded image)

Returns message to indicate successful completion / error message.

**Comment by katrina-barth** [comment]
Strings for identifying what image processing method to use:
"Hist"
"Contrast"
"Log"
"Reverse"

**Comment by katrina-barth** [comment]
Field = "Method" (so example dictionary looks like "Method": "Hist")

**Comment by katrina-barth** [comment]
Is there anything special that the user ID should be? Should the user enter their ID?

**Comment by katrina-barth** [comment]
Also, I made "method" lowercase in my dictionary

**Comment by minhajh** [comment]
Just a string - I think the user should enter their ID - you should then send a post request to the server route "/api/register_user" with a dict with the field 'user_id' and store that string locally to send requests to the server (i.e. every dictionary submitted to the server should have the field 'user_id' : "some user id string").

**Comment by katrina-barth** [comment]
A third option for "method": is "none"

**Comment by katrina-barth** [comment]
original and processed image dictionary tags:
original_image:
processed_image:

**Comment by IakovRach** [comment]
Client and Server are communicating.
