### ISSUE TITLE
Image Encoding / Decoding Operations

### ISSUE THREAD

**Issue by minhajh** [mhuss93/bme547final#36]
- [ ] Encode image as base64 string.

- [ ] Decode base64 string as image.

**Comment by minhajh** [comment]
Where are we with the image encoding / decoding operations? I can finish up the server / database side once I have them.

**Comment by IakovRach** [comment]
Hey,

I've been having trouble with the matrix version functions. I'm gonna be working on it again tonight.

It's not outputting the right format and haven't find solution yet.

I'll let you know progress tonight.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by katrina-barth** [comment]
I've got it working now within my GUI (encode image from file, decode into numpy array, convert to Pillow image object, save as file). My next commit is going to be writing JSON files with the encoded images and the other stuff we talked about including. @mhuss93 is that helpful for you in the database side? You could then use the JSON files my GUI writes to test putting into the database maybe?

**Comment by minhajh** [comment]
Ideal. Yep, the server/database side of things is mostly built (just need to plug in the image manipulation functions and encoding/decoding and some data requests e.g. for the average time it takes to run a particular image processing step, etc.)

**Comment by IakovRach** [comment]
encoding decoding works: encode_decode.py
